### ISSUE TITLE
[1.15.2] Skeleton Villagers naturally spawning in The Midnight dimension (v1.1.2)

### ISSUE THREAD

**Issue by sirgfsa** [Farcr/SavageAndRavage#10]
Minecraft: 1.15.2
Forge Version: 31.2.0
Mods Used: 
Abnormals-Core-1.15.2-v1.0.5.jar
Savage-and-Ravage-1.15.2-v1.1.2.jar
themidnight-0.5.9.jar
![2020-06-06_11 58 20](https://user-images.githubusercontent.com/66380400/83935552-39617f00-a7ed-11ea-8f3a-e7faae2a0512.png)

**Comment by seymourimadeit** [comment]
fixed  9b1d09c
