### ISSUE TITLE
[1.15.2]raid don't happens (v1.1.2)

### ISSUE THREAD

**Issue by bucketBrian** [Farcr/SavageAndRavage#11]
I was burning illager flags to get bad omen affect.
But when I was went to the village the raid just don't happen and the affect don't disappear too.
forge version: 31.2.8

[latest.log](https://github.com/Farcr/SavageAndRavage/files/4758629/latest.log)

**Comment by seymourimadeit** [comment]
are you on peaceful

**Comment by bucketBrian** [comment]
oh, yes. I just find out I was in peaceful...
