### ISSUE TITLE
Skeleton villagers spawning in modded dimensions.

### ISSUE THREAD

**Issue by DeadPigman17** [Farcr/SavageAndRavage#12]
As far as I know, they spawn in these dimensions:
-The Bumblezone's dimension
-The Midnight's dimension
-Rediscovered's Skylands dimension
It'd be handy if you added a config option to blacklist which dimension Skeleton villagers can spawn on. Or you can also make them unable to spawn in any dimension besides the Overworld.

**Comment by seymourimadeit** [comment]
duplicate #10
