### ISSUE TITLE
PIllager crash

### ISSUE THREAD

**Issue by AngrySammy** [Farcr/SavageAndRavage#13]
This crash happens in Multiplayer when a player gets too close to a pillager in survival mode.
https://gist.github.com/AngrySammy/c21f21836866dfc87e38dfa19744f086

**Comment by solarblindfull** [comment]
Hello ! Thank for this very good mod. 
Unfortunately, I have exactly the same crash here. Thank for your report @AngrySammy. Can you see what's wrong please ?

**Comment by itsTort** [comment]
Can confirm, I am having the same issue with Pillagers.  Seems like the game crashes when you get too close in Survival Mode and they shoot a crossbow at you?  Here is my crash report:

https://pastebin.com/tXievhhE

**Comment by Divineaspect** [comment]
and my axe!

**Comment by Voliant** [comment]
Fixed in 420bf10, will release on CurseForge in a few days if no other bugs appear.

**Comment by ComedyArbiter** [comment]
[The update is out.](https://www.curseforge.com/minecraft/mc-mods/savage-and-ravage/files/2997084)

**Comment by solarblindfull** [comment]
Thank very much !
