### ISSUE TITLE
Skeleton Villager Crash

### ISSUE THREAD

**Issue by SaikoChan1** [Farcr/SavageAndRavage#14]
Skeleton Villager loads crossbow and instantly crashes game, might be cause of too many mods but unsure

https://hastebin.com/pimofolade.pl

**Comment by seymourimadeit** [comment]
>at com.stereowalker.combat.compat.curios.quiver.CurioQuiverCrossbow.fireCrossbowArrowFromQuiver(CurioQuiverCrossbow.java:38) ~[?:1.15.2-4.8.8] {re:classloading}

this crash seems to be caused by the curios mod it seems.

**Comment by SaikoChan1** [comment]
Removed all curios mods and it still crashes 

https://hastebin.com/awaviwaneh.pl

**Comment by bageldotjpg** [comment]
That is a different crash unrelated to Savage and Ravage
