### ISSUE TITLE
[Multiplayer] Crash on pillager spawns

### ISSUE THREAD

**Issue by dreckz** [Farcr/SavageAndRavage#15]
MC: 1.15.2
Forge: 31.2.29
SaR: v1.1.3

My server recently has been crashing a decent amount while my players are playing.  I noticed in the console that SaR was having a problem with a ticking entity from SaR.  I tried spawning a couple of pillagers, and the mod just crashes the server, and I repeated this 2 times.  At first I thought it was the mod performant, but it didn't seem to be that. Here is the crash report:

[crash-2020-07-04_14.03.08-server.txt](https://github.com/Farcr/SavageAndRavage/files/4873570/crash-2020-07-04_14.03.08-server.txt)
[crash-2020-07-04_14.10.44-server.txt](https://github.com/Farcr/SavageAndRavage/files/4873571/crash-2020-07-04_14.10.44-server.txt)

**Comment by ComedyArbiter** [comment]
[Fixed in the latest update](https://www.curseforge.com/minecraft/mc-mods/savage-and-ravage/files/2997084)
