### ISSUE TITLE
[Multiplayer]

### ISSUE THREAD

**Issue by ShinySilver** [Farcr/SavageAndRavage#16]
I'm running this mod on my server, and I think it *may be* an incompatibility between savage&ravage and immersive portals
Logs here: https://paste.ubuntu.com/p/FkgVY2wVDk/ I'm using the last forge version.
How to reproduce this bug? Find a pillager, he will attack you normally. But if you go just next to them, the server will crash.
Adding a small config option to disable small features to ensure compatibility with immersive portal would be very great :3
Ty for your hard work: :D

**Comment by Farcr** [comment]
We fixed this bug in dev! We're releasing a patch that fixes it very soon!

**Comment by ComedyArbiter** [comment]
[The patch is out!](https://www.curseforge.com/minecraft/mc-mods/savage-and-ravage/files/2997084)

**Comment by ComedyArbiter** [comment]
By the way, it had nothing to do with immersive portals. We hadn't noticed that a method we were calling when the player got close to a pillager didn't exist serverside.

**Comment by ShinySilver** [comment]
Thanks 👍 I've never used Mixin, so I didn't know how to interpret the presence of immersive portal in the error message. I'll spend some time to look into your mod source code to understand how mixin works ^^
