### ISSUE TITLE
Server crash "Failed to load hierarchy member net/minecraft/entity/IChargeableMob"

### ISSUE THREAD

**Issue by FuryOfFools** [Farcr/SavageAndRavage#2]
[crash-2020-05-08_14.34.53-server.txt](https://github.com/Farcr/SavageAndRavage/files/4598467/crash-2020-05-08_14.34.53-server.txt)

**Comment by NJL5390** [comment]
Can confirm that I am also getting this same issue. It occurs whenever I attempt to start a server with this mod installed. This crash does not occur client-side.

Crash Report:
[crash-2020-05-08_18.45.59-server.txt](https://github.com/Farcr/SavageAndRavage/files/4600658/crash-2020-05-08_18.45.59-server.txt)

**Comment by seymourimadeit** [comment]
fixed 5fe2e44
