### ISSUE TITLE
Creepies stop when exploding when Performant is installed

### ISSUE THREAD

**Issue by Insane96** [Farcr/SavageAndRavage#4]
They behave like normal Creepers when exploding, they stop moving.

**Comment by Voliant** [comment]
1. Can you post a video of this?
2. Which version are you on?

**Comment by Insane96** [comment]
Tested the mod alone and doesn't seem to happen, I'll try to understand which mod causes that.

**Comment by Insane96** [comment]
One hit one shot.
The Performant mod does something to their AI and makes them behave like normal creepers

**Comment by Voliant** [comment]
I'll look into it, thanks.

**Comment by Voliant** [comment]
Wait i didn't mean to close

**Comment by Voliant** [comment]
Are you still having this issue in the mod's latest release? (1.0.2)

**Comment by Insane96** [comment]
I did the test in 1.0.2, so yep

**Comment by Voliant** [comment]
Hi, I've found what causes this issue - it seems to be a consequence of [a feature limiting paths created to 1 per second](https://github.com/ldtteam/Performant/issues/40) which you can solve by turning off the `fastPathFinding` option in performant's config.
