### ISSUE TITLE
Something about the skeleton villagers 

### ISSUE THREAD

**Issue by SantosGG1810** [Farcr/SavageAndRavage#6]
The mod is very good, just that at the moment there is something that I do not like so much, it is very small but I would like you to change it, the skeleton villager has pixels that move constantly and bothers a little, they are like half of his body, just above his legs

**Comment by Voliant** [comment]
Fixed [001d30f](https://github.com/Farcr/SavageAndRavage/commit/001d30fedc073f1d1932017ee5129e5ceca7a08e).
