### ISSUE TITLE
Spore Bomb Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Farcr/SavageAndRavage#7]
`Minecraft v1.15.2`
`Forge v31.2.5`
`Savage & Ravage v1.1.1`

My server crashed right after I lit a Spore Bomb using Flint & Steel.
[Crash Report](https://gist.github.com/WenXin20/2e91dfe9140bc1ef89311edc72b06dc9)

**Comment by MiguelWaffles** [comment]
Mine too https://pastebin.com/VMbXvKhH

**Comment by bageldotjpg** [comment]
Should be fixed as of 1.1.2. Reopen if not.
